### ISSUE TITLE
Response for preflight has invalid HTTP status code 500

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#2096]
### Issue Description

I'm using Parse within an angular2 app. So far I was running on parse server 2.2.10 but since updating to 2.2.13 my `http.get()` calls are failing with following error:
```
XMLHttpRequest cannot load http:/my-parse-domain/parse/classes/MyClass
Response for preflight has invalid HTTP status code 500
```

The JS/TS code looks something like this:
```
var headers = new Headers();
headers.append('X-Parse-Application-Id', 'myAppId');

this.http.get('http:/my-parse-domain/parse/classes/MyClass', {
  headers: headers
}).map(res => {
    return res.json().results;
})
.subscribe(data => {
...
```

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Setup an angular2 app
2. Try to get a class using the angular2 http provider

#### Expected Results

JSON response with the class

#### Actual Outcome

`Response for preflight has invalid HTTP status code 500`
(see: http://stackoverflow.com/questions/34461724/authentication-error-response-for-preflight-has-invalid-http-status-code-405)

### Environment Setup

- **Server**
  - parse-server version: 2.2.13
  - Operating System:  Amazon Linux
  - Hardware: AWS Elastic Beanstalk with EC2 small instances
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.2.3
  - Storage engine: wiredtiger
  - Hardware: AWS
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Scalegrid

**Comment by codebreach** [comment]
This is most likely caused by the OPTIONS preflight call to the backend to get CORS headers. (as described in the stackoverflow link as well)

Can you try running the server with VERBOSE=1 environment variable set and copy paste those logs.

Also- where are you running your angular2 app? is it served on the same hostname as the server or a different hostname?

**Comment by flavordaaave** [comment]
@codebreach I'm running the angular2 app on a different host. Here's the error that is put out in verbose mode:
```
error: Uncaught internal server error. [TypeError: res.sendStatus is not a function] TypeError: res.sendStatus is not a function
    at allowCrossDomain (/Users/david/Projects/parse-server/node_modules/parse-server/lib/middlewares.js:205:9)
    at Layer.handle [as handle_request] (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:312:13)
    at /Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:312:13)
    at /Users/david/Projects/parse-server/node_modules/parse-server/node_modules/express/lib/router/index.js:280:7
```

As mentioned, everything is working with parse-server version 2.10.10. I did some further testing and it seems that the error is popping up since version 2.10.11.

**Comment by codebreach** [comment]
The issue is that `res.sendStatus` has been deprecated and should be updated to `res.status().send()`

I am getting a PR out to fix this. It should be a oneliner

**Comment by flovilmart** [comment]
What version of expressjs are you running?

**Comment by flavordaaave** [comment]
@flovilmart 
`"version": "4.2.0"`

**Comment by codebreach** [comment]
I can't get a test to fail and `sendStatus` is NOT deprecated. I confused a warning from an older express 3.x project.
I have seen weird errors like this when conflicting versions of packages are installed.

Can you try doing an `npm ls` and consider `npm prune` (which will remove packages not defined in pacakge.json)
also what version of `npm` and `node` are you using?

**Comment by flavordaaave** [comment]
@codebreach 
npm: 2.14.4
node: v5.10.1 
This is the full output of `npm ls`:
```
├─┬ express@4.2.0
│ ├─┬ accepts@1.0.1
│ │ ├── mime@1.2.11
│ │ └── negotiator@0.4.9
│ ├── buffer-crc32@0.2.1
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.3
│ ├── debug@0.8.1
│ ├── escape-html@1.0.1
│ ├── fresh@0.2.2
│ ├── merge-descriptors@0.0.2
│ ├── methods@1.0.0
│ ├── parseurl@1.0.1
│ ├── path-to-regexp@0.1.2
│ ├── qs@0.6.6
│ ├── range-parser@1.0.0
│ ├─┬ send@0.3.0
│ │ ├── debug@0.8.0
│ │ └── mime@1.2.11
│ ├── serve-static@1.1.0
│ ├─┬ type-is@1.1.0
│ │ └── mime@1.2.11
│ └── utils-merge@1.0.0
├─┬ parse@1.8.5
│ ├─┬ babel-runtime@5.8.38
│ │ └── core-js@1.2.6
│ ├─┬ ws@1.1.0
│ │ ├── options@0.0.6
│ │ └── ultron@1.0.2
│ └── xmlhttprequest@1.8.0
└─┬ parse-server@2.2.14
  ├─┬ babel-polyfill@6.8.0
  │ ├── babel-regenerator-runtime@6.5.0
  │ └── core-js@2.4.0
  ├─┬ babel-runtime@6.6.1
  │ └── core-js@2.4.0
  ├── bcrypt-nodejs@0.0.3
  ├─┬ body-parser@1.15.2
  │ ├── bytes@2.4.0
  │ ├── content-type@1.0.2
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── depd@1.1.0
  │ ├─┬ http-errors@1.5.0
  │ │ ├── inherits@2.0.1
  │ │ ├── setprototypeof@1.0.1
  │ │ └── statuses@1.3.0
  │ ├── iconv-lite@0.4.13
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── qs@6.2.0
  │ ├─┬ raw-body@2.1.7
  │ │ └── unpipe@1.0.0
  │ └─┬ type-is@1.6.13
  │   ├── media-typer@0.3.0
  │   └─┬ mime-types@2.1.11
  │     └── mime-db@1.23.0
  ├── colors@1.1.2
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├── deepcopy@0.6.3
  ├─┬ express@4.14.0
  │ ├─┬ accepts@1.3.3
  │ │ ├─┬ mime-types@2.1.11
  │ │ │ └── mime-db@1.23.0
  │ │ └── negotiator@0.6.1
  │ ├── array-flatten@1.1.1
  │ ├── content-disposition@0.5.1
  │ ├── content-type@1.0.2
  │ ├── cookie@0.3.1
  │ ├── cookie-signature@1.0.6
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── depd@1.1.0
  │ ├── encodeurl@1.0.1
  │ ├── escape-html@1.0.3
  │ ├── etag@1.7.0
  │ ├─┬ finalhandler@0.5.0
  │ │ ├── statuses@1.3.0
  │ │ └── unpipe@1.0.0
  │ ├── fresh@0.3.0
  │ ├── merge-descriptors@1.0.1
  │ ├── methods@1.1.2
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── parseurl@1.3.1
  │ ├── path-to-regexp@0.1.7
  │ ├─┬ proxy-addr@1.1.2
  │ │ ├── forwarded@0.1.0
  │ │ └── ipaddr.js@1.1.1
  │ ├── qs@6.2.0
  │ ├── range-parser@1.2.0
  │ ├─┬ send@0.14.1
  │ │ ├── destroy@1.0.4
  │ │ ├─┬ http-errors@1.5.0
  │ │ │ ├── inherits@2.0.1
  │ │ │ └── setprototypeof@1.0.1
  │ │ ├── ms@0.7.1
  │ │ └── statuses@1.3.0
  │ ├── serve-static@1.11.1
  │ ├─┬ type-is@1.6.13
  │ │ ├── media-typer@0.3.0
  │ │ └─┬ mime-types@2.1.11
  │ │   └── mime-db@1.23.0
  │ ├── utils-merge@1.0.0
  │ └── vary@1.1.0
  ├── intersect@1.0.1
  ├── lodash@4.12.0
  ├─┬ lru-cache@4.0.1
  │ ├── pseudomap@1.0.2
  │ └── yallist@2.0.0
  ├─┬ mailgun-js@0.7.10
  │ ├── async@1.5.2
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├─┬ form-data@1.0.0-rc4
  │ │ ├─┬ combined-stream@1.0.5
  │ │ │ └── delayed-stream@1.0.0
  │ │ └─┬ mime-types@2.1.11
  │ │   └── mime-db@1.23.0
  │ ├── inflection@1.7.2
  │ ├─┬ path-proxy@1.0.0
  │ │ └── inflection@1.3.8
  │ ├─┬ proxy-agent@2.0.0
  │ │ ├─┬ agent-base@2.0.1
  │ │ │ └── semver@5.0.3
  │ │ ├── extend@3.0.0
  │ │ ├── http-proxy-agent@1.0.0
  │ │ ├── https-proxy-agent@1.0.0
  │ │ ├── lru-cache@2.6.5
  │ │ ├─┬ pac-proxy-agent@1.0.0
  │ │ │ ├─┬ get-uri@1.1.0
  │ │ │ │ ├── data-uri-to-buffer@0.0.4
  │ │ │ │ ├── file-uri-to-path@0.0.2
  │ │ │ │ ├─┬ ftp@0.3.10
  │ │ │ │ │ ├─┬ readable-stream@1.1.14
  │ │ │ │ │ │ ├── core-util-is@1.0.2
  │ │ │ │ │ │ ├── inherits@2.0.1
  │ │ │ │ │ │ ├── isarray@0.0.1
  │ │ │ │ │ │ └── string_decoder@0.10.31
  │ │ │ │ │ └── xregexp@2.0.0
  │ │ │ │ └─┬ readable-stream@2.1.4
  │ │ │ │   ├── buffer-shims@1.0.0
  │ │ │ │   ├── core-util-is@1.0.2
  │ │ │ │   ├── inherits@2.0.1
  │ │ │ │   ├── isarray@1.0.0
  │ │ │ │   ├── process-nextick-args@1.0.7
  │ │ │ │   ├── string_decoder@0.10.31
  │ │ │ │   └── util-deprecate@1.0.2
  │ │ │ ├─┬ pac-resolver@1.2.6
  │ │ │ │ ├── co@3.0.6
  │ │ │ │ ├─┬ degenerator@1.0.3
  │ │ │ │ │ ├── ast-types@0.8.18
  │ │ │ │ │ ├─┬ escodegen@1.8.0
  │ │ │ │ │ │ ├── estraverse@1.9.3
  │ │ │ │ │ │ ├── esutils@2.0.2
  │ │ │ │ │ │ ├─┬ optionator@0.8.1
  │ │ │ │ │ │ │ ├── deep-is@0.1.3
  │ │ │ │ │ │ │ ├── fast-levenshtein@1.1.3
  │ │ │ │ │ │ │ ├── levn@0.3.0
  │ │ │ │ │ │ │ ├── prelude-ls@1.1.2
  │ │ │ │ │ │ │ ├── type-check@0.3.2
  │ │ │ │ │ │ │ └── wordwrap@1.0.0
  │ │ │ │ │ │ └─┬ source-map@0.2.0
  │ │ │ │ │ │   └── amdefine@1.0.0
  │ │ │ │ │ └── esprima@2.7.2
  │ │ │ │ ├── netmask@1.0.6
  │ │ │ │ ├─┬ regenerator@0.8.46
  │ │ │ │ │ ├─┬ commoner@0.10.4
  │ │ │ │ │ │ ├─┬ detective@4.3.1
  │ │ │ │ │ │ │ ├── acorn@1.2.2
  │ │ │ │ │ │ │ └── defined@1.0.0
  │ │ │ │ │ │ ├─┬ glob@5.0.15
  │ │ │ │ │ │ │ ├─┬ inflight@1.0.5
  │ │ │ │ │ │ │ │ └── wrappy@1.0.2
  │ │ │ │ │ │ │ ├── inherits@2.0.1
  │ │ │ │ │ │ │ ├─┬ minimatch@3.0.2
  │ │ │ │ │ │ │ │ └─┬ brace-expansion@1.1.5
  │ │ │ │ │ │ │ │   ├── balanced-match@0.4.1
  │ │ │ │ │ │ │ │   └── concat-map@0.0.1
  │ │ │ │ │ │ │ ├─┬ once@1.3.3
  │ │ │ │ │ │ │ │ └── wrappy@1.0.2
  │ │ │ │ │ │ │ └── path-is-absolute@1.0.0
  │ │ │ │ │ │ ├── graceful-fs@4.1.4
  │ │ │ │ │ │ ├── iconv-lite@0.4.13
  │ │ │ │ │ │ └─┬ mkdirp@0.5.1
  │ │ │ │ │ │   └── minimist@0.0.8
  │ │ │ │ │ ├─┬ defs@1.1.1
  │ │ │ │ │ │ ├─┬ alter@0.2.0
  │ │ │ │ │ │ │ └── stable@0.1.5
  │ │ │ │ │ │ ├── ast-traverse@0.1.1
  │ │ │ │ │ │ ├── breakable@1.0.0
  │ │ │ │ │ │ ├── simple-fmt@0.1.0
  │ │ │ │ │ │ ├── simple-is@0.2.0
  │ │ │ │ │ │ ├── stringmap@0.2.2
  │ │ │ │ │ │ ├── stringset@0.2.1
  │ │ │ │ │ │ ├── tryor@0.1.2
  │ │ │ │ │ │ └─┬ yargs@3.27.0
  │ │ │ │ │ │   ├── camelcase@1.2.1
  │ │ │ │ │ │   ├─┬ cliui@2.1.0
  │ │ │ │ │ │   │ ├─┬ center-align@0.1.3
  │ │ │ │ │ │   │ │ ├─┬ align-text@0.1.4
  │ │ │ │ │ │   │ │ │ ├─┬ kind-of@3.0.3
  │ │ │ │ │ │   │ │ │ │ └── is-buffer@1.1.3
  │ │ │ │ │ │   │ │ │ ├── longest@1.0.1
  │ │ │ │ │ │   │ │ │ └── repeat-string@1.5.4
  │ │ │ │ │ │   │ │ └── lazy-cache@1.0.4
  │ │ │ │ │ │   │ ├─┬ right-align@0.1.3
  │ │ │ │ │ │   │ │ └─┬ align-text@0.1.4
  │ │ │ │ │ │   │ │   ├─┬ kind-of@3.0.3
  │ │ │ │ │ │   │ │   │ └── is-buffer@1.1.3
  │ │ │ │ │ │   │ │   ├── longest@1.0.1
  │ │ │ │ │ │   │ │   └── repeat-string@1.5.4
  │ │ │ │ │ │   │ └── wordwrap@0.0.2
  │ │ │ │ │ │   ├── decamelize@1.2.0
  │ │ │ │ │ │   ├─┬ os-locale@1.4.0
  │ │ │ │ │ │   │ └─┬ lcid@1.0.0
  │ │ │ │ │ │   │   └── invert-kv@1.0.0
  │ │ │ │ │ │   ├── window-size@0.1.4
  │ │ │ │ │ │   └── y18n@3.2.1
  │ │ │ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
  │ │ │ │ │ ├── private@0.1.6
  │ │ │ │ │ ├─┬ recast@0.10.33
  │ │ │ │ │ │ ├── ast-types@0.8.12
  │ │ │ │ │ │ └── source-map@0.5.6
  │ │ │ │ │ ├── regenerator-runtime@0.9.5
  │ │ │ │ │ └── through@2.3.8
  │ │ │ │ └── thunkify@2.1.2
  │ │ │ └─┬ stream-to-buffer@0.1.0
  │ │ │   └── stream-to@0.2.2
  │ │ └─┬ socks-proxy-agent@2.0.0
  │ │   └─┬ socks@1.1.9
  │ │     ├── ip@1.1.3
  │ │     └── smart-buffer@1.0.11
  │ ├── q@1.4.1
  │ └── scmp@1.0.0
  ├── mime@1.3.4
  ├─┬ mongodb@2.1.18
  │ ├── es6-promise@3.0.2
  │ ├─┬ mongodb-core@1.3.18
  │ │ ├── bson@0.4.23
  │ │ └─┬ require_optional@1.0.0
  │ │   ├── resolve-from@2.0.0
  │ │   └── semver@5.2.0
  │ └─┬ readable-stream@1.0.31
  │   ├── core-util-is@1.0.2
  │   ├── inherits@2.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├─┬ multer@1.1.0
  │ ├── append-field@0.1.0
  │ ├─┬ busboy@0.2.13
  │ │ ├─┬ dicer@0.2.5
  │ │ │ └── streamsearch@0.1.2
  │ │ └─┬ readable-stream@1.1.14
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├─┬ concat-stream@1.5.1
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├── object-assign@3.0.0
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├─┬ type-is@1.6.13
  │ │ ├── media-typer@0.3.0
  │ │ └─┬ mime-types@2.1.11
  │ │   └── mime-db@1.23.0
  │ └── xtend@4.0.1
  ├─┬ parse-server-fs-adapter@1.0.0
  │ ├─┬ jasmine@2.4.1
  │ │ ├── exit@0.1.2
  │ │ ├─┬ glob@3.2.11
  │ │ │ ├── inherits@2.0.1
  │ │ │ └─┬ minimatch@0.3.0
  │ │ │   ├── lru-cache@2.7.3
  │ │ │   └── sigmund@1.0.1
  │ │ └── jasmine-core@2.4.1
  │ └── parse-server-conformance-tests@1.0.0
  ├─┬ parse-server-push-adapter@1.0.4
  │ ├─┬ apn@1.7.6
  │ │ ├─┬ debug@2.2.0
  │ │ │ └── ms@0.7.1
  │ │ ├── node-forge@0.6.40
  │ │ └── q@1.4.1
  │ ├─┬ node-gcm@0.14.3
  │ │ ├── debug@0.8.1
  │ │ └── lodash@3.10.1
  │ └─┬ npmlog@2.0.4
  │   ├── ansi@0.3.1
  │   ├─┬ are-we-there-yet@1.1.2
  │   │ ├── delegates@1.0.0
  │   │ └─┬ readable-stream@2.1.4
  │   │   ├── buffer-shims@1.0.0
  │   │   ├── core-util-is@1.0.2
  │   │   ├── inherits@2.0.1
  │   │   ├── isarray@1.0.0
  │   │   ├── process-nextick-args@1.0.7
  │   │   ├── string_decoder@0.10.31
  │   │   └── util-deprecate@1.0.2
  │   └─┬ gauge@1.2.7
  │     ├── has-unicode@2.0.1
  │     ├─┬ lodash.pad@4.4.0
  │     │ ├── lodash._baseslice@4.0.0
  │     │ ├── lodash._basetostring@4.12.0
  │     │ └── lodash.tostring@4.1.3
  │     ├─┬ lodash.padend@4.5.0
  │     │ ├── lodash._baseslice@4.0.0
  │     │ ├── lodash._basetostring@4.12.0
  │     │ └── lodash.tostring@4.1.3
  │     └─┬ lodash.padstart@4.5.0
  │       ├── lodash._baseslice@4.0.0
  │       ├── lodash._basetostring@4.12.0
  │       └── lodash.tostring@4.1.3
  ├─┬ parse-server-s3-adapter@1.0.3
  │ └─┬ aws-sdk@2.4.4
  │   ├── jmespath@0.15.0
  │   ├── sax@1.1.5
  │   ├── xml2js@0.4.15
  │   └─┬ xmlbuilder@2.6.2
  │     └── lodash@3.5.0
  ├── parse-server-simple-mailgun-adapter@1.0.0
  ├─┬ pg-promise@4.8.0
  │ ├── manakin@0.3.0
  │ ├─┬ pg@5.1.0
  │ │ ├── buffer-writer@1.0.1
  │ │ ├── generic-pool@2.4.2
  │ │ ├── packet-reader@0.2.0
  │ │ ├── pg-connection-string@0.1.3
  │ │ ├─┬ pg-types@1.11.0
  │ │ │ ├── ap@0.2.0
  │ │ │ ├── postgres-array@1.0.0
  │ │ │ ├── postgres-bytea@1.0.0
  │ │ │ ├── postgres-date@1.0.2
  │ │ │ └─┬ postgres-interval@1.0.2
  │ │ │   └── xtend@4.0.1
  │ │ ├─┬ pgpass@0.0.6
  │ │ │ └─┬ split@1.0.0
  │ │ │   └── through@2.3.8
  │ │ └── semver@4.3.2
  │ ├── pg-minify@0.3.3
  │ └── spex@0.4.6
  ├─┬ redis@2.6.2
  │ ├── double-ended-queue@2.1.0-0
  │ ├── redis-commands@1.2.0
  │ └── redis-parser@2.0.3
  ├─┬ request@2.72.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.4.1
  │ ├─┬ bl@1.1.2
  │ │ └─┬ readable-stream@2.0.6
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── string_decoder@0.10.31
  │ │   └── util-deprecate@1.0.2
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc4
  │ │ └── async@1.5.2
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ is-my-json-valid@2.13.1
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.0
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.2
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.8.3
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── dashdash@1.14.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├── getpass@0.1.6
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.13.3
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.11
  │ │ └── mime-db@1.23.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.1.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.2
  │ └── tunnel-agent@0.4.3
  ├─┬ request-promise@3.0.0
  │ └── bluebird@3.4.1
  ├── tv4@1.2.7
  ├─┬ winston@2.2.0
  │ ├── async@1.0.0
  │ ├── colors@1.0.3
  │ ├── cycle@1.0.3
  │ ├── eyes@0.1.8
  │ ├── isstream@0.1.2
  │ ├── pkginfo@0.3.1
  │ └── stack-trace@0.0.9
  ├─┬ winston-daily-rotate-file@1.0.1
  │ └─┬ winston@2.1.1
  │   ├── async@1.0.0
  │   ├── colors@1.0.3
  │   ├── cycle@1.0.3
  │   ├── eyes@0.1.8
  │   ├── isstream@0.1.2
  │   ├── pkginfo@0.3.1
  │   └── stack-trace@0.0.9
  └─┬ ws@1.0.1
    ├── options@0.0.6
    └── ultron@1.0.2
``

**Comment by flavordaaave** [comment]
@codebreach I actually just did a quick test and replaced 

```
res.sendStatus(200);
```
with
```
 res.status(200).send('OK')
```

in /lib/middlewares.js:205

and it is working. So `sendStatus` seems to be the problem here.

**Comment by codebreach** [comment]
You have two versions of express installed. Can you downgrade your top
level dependency to the one parse server uses or add a shrinkwrap file to
force parse server to use your version?

Parse server uses 4.14 and you are on 4.2 both of which should have
sendStatus in them so I am not sure how much milage this will really get.

**Comment by hramos** [comment]
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.
